### ISSUE TITLE
Calling "update" before reading store at least once always returns initial data in callback

### ISSUE THREAD

**Issue by dimdenGD** [joshnuss/svelte-persisted-store#231]
If you immediately use `.update` on the store, without subscribing/getting it at least once, data inside callback will always be initial data.
Example:
```js
let store = persisted("test", { init: true });
store.update(data => {
    console.log(data.init);
    data.init = false;
    return data;
});
```
Refreshing tab will always show `true`
but if you add get:
```js
let store = persisted("test", { init: true });
get(store);
store.update(data => {
    console.log(data.init);
    data.init = false;
    return data;
});
```
it starts working properly and shows `false`

**Comment by joshnuss** [comment]
Hi @dimdenGD!

I tried to reproduce the issue in SvelteLab, but cannot recreate the error:

https://www.sveltelab.dev/xxzgev06as3agrk

Is there any errors in your console?
What is the value of the store in local storage?
Note, you forgot to return a value in the `update()` callback. Maybe that has caused `undefined` to be set in local storage?

**Comment by dimdenGD** [comment]
Hi.
- There are no errors
- Value gets changed fine, its just that on first time it always returns initial value instead of stored value.
- This is a mistype, I do return it properly in my code.
I checked your SvelteLab and I'm not sure why it doesn't happen there, I created a small project that reproduces the issue:
[persisted-bug.zip](https://github.com/joshnuss/svelte-persisted-store/files/13834122/persisted-bug.zip)

**Comment by dimdenGD** [comment]
Oh, your project doesn't recreate the issue because you use $ to read from store, if you comment out these out and check console issue starts to happen

**Comment by joshnuss** [comment]
Thanks for reporting and diagnosis @dimdenGD!

The issue is now resolved.

It was caused because when a closure is passed to a `writable()` store, the closure is lazily executed. That means until a `get()` happened, it never ran the closure and didn't load the value from local storage.

**Comment by dimdenGD** [comment]
Thanks for the quick fix!
