### ISSUE TITLE
TS export needed?

### ISSUE THREAD

**Issue by cycle4passion** [joshnuss/svelte-persisted-store#281]
I am no typescript wizard to say the least, and had red squiggle everywhere. 

Looking in the node modules types for svelte-persisted-store, shouldn't the Persisted type be exported?

for use like...

```js
const books: Persisted<BookType[]> = persisted("books", []);
```

**Comment by joshnuss** [comment]
Hi @cycle4passion!

what about:

```ts
const books = persisted<BookType[]>("books", [])
```

**Comment by joshnuss** [comment]
But yeah, I think it should be exported, PR incoming.
