### ISSUE TITLE
Feature request: add some built-in handling of binary buffers

### ISSUE THREAD

**Issue by martinpaljak** [joshnuss/svelte-persisted-store#292]
After some struggling with storing uint8arrays, I ended up adding a cbor+base64 step. Would be lovely if there was something built in that could be enabled by some simple boolean option, but I have no great ideas how to enable it in a "universal and pure way".

**Comment by martinpaljak** [comment]
I did. For me cbor is a natural choice and works well, to give a "sane" result. Yet the way the default serializer (JSON) works (not specific to this svelte store project but in general) for arraybuffers/uint8arrays seems to raise quite a few questions, so it might be useful to have something simple, generic, dependency free and documented, like `{binary: true}` in `options`.

For the reference, this is what worked for me:

```javascript
import { decode, encode } from 'cborg';

const cbor_base64 = {
	stringify: function(v) {
		return ab2base64url(encode(v));
	},
	parse: function(v) {
		return decode(base64url2u8(v));
	}
} as Serializer<State>;

export const card = persisted<State>('state', init('unknown', {}), {
	serializer: cbor_base64
});
```

**Comment by joshnuss** [comment]
My preference is to use a custom serializer for this, like you did.

Custom serializer ate designed precisely for situations like these, where the default JSON serialization doesn't work.

The challenge with adding nore options, is if I allow everyone to add their special cases this library will become harder to use.

So I'm closing for now.

 If others run into this issue, please comment below, and I am open to changing my mind if many folks request this

**Comment by martinpaljak** [comment]
Round-trip consistency of save&load cycle could be something desirable (maybe even something expected), so maybe my focus with "binary" is not the right naming. I'm happy with having my own serializers in a few lines that make it happen _for me_, but the "principle of least surprise" option out of the box might be something worth considering nevertheless.
